✨ Ajoute un historique des IMC.
Zenika/labs-svelte pull request #41
Opened 2022-04-08 15:14 UTC by patou

@anthonylegoas 
Qu'en pense tu modifier la partie sur les events submit pour enregistrer les valeurs dans une liste avec une date.
Cela sera un bout de code qui ne sera pas remplacé. par autre chose.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/841858/162471602-73670620-a175-4246-8f40-2169aad5b40e.png">

2022-04-10 08:26 UTC, anthonylegoas commented
Pourquoi pas oui 👍

2022-04-15 14:57 UTC, anthonylegoas requested changes
J'ai mis quelques petites suggestions, en supprimant notamment le champ input "date" qui n'apporte pas grand chose je trouve.

2022-04-15 14:57 UTC, anthonylegoas commented on become-svelte/src/lib/Form.svelte
> +  </label>
Je n'aurais pas mis l'input date, je trouve que ça n'apporte pas grand, ça n'introduit pas de nouvelle fonctionnalité de Svelte qu'on aurait pas vu jusque là.

Et ensuite dans le `handleSubmit` on peut dispatch un event avec la date comme ça : `date: new Date(),`

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +Ajoutons maintenant la possibilité de sauvegarder notre IMC a différente date. Pour cela il est nécessaire d'ajouter dans notre formulaire un champ de type date et un bouton sauvegarder.
```suggestion
Ajoutons maintenant la possibilité de sauvegarder notre IMC. Pour cela il est nécessaire d'ajouter un bouton `Sauvegarder` dans notre formulaire.
```

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +  <button type="submit">Sauvegarder</button>
```suggestion
  <button type="submit">Sauvegarder</button>
```

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +			date: event.target.date.value || new Date(),
```suggestion
			date: new Date(),
```

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +  <button type="submit">Sauvegarder</button>
```suggestion
  <button type="submit">Sauvegarder</button>
```

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +En testant notre code, vous remarquerez que l'historique ne s'affiche pas en cliquant sur le bouton. C'est parce que _Svelte_ utilise l'affectation d'une variable pour savoir quand une donné est modi
```suggestion
En testant notre code, vous remarquerez que l'historique ne s'affiche pas en cliquant sur le bouton. C'est parce que _Svelte_ utilise l'affectation d'une variable pour savoir quand une donnée est modifiée. Or lorsque l'on fait un push sur notre tableau, la variable n'est pas modifiée et donc _Svelte_ ne détecte pas la modification.
```

2022-04-15 14:57 UTC, anthonylegoas commented on codelab/codelab.md
> +    <button type="submit">Sauvegarder</button>
```suggestion
    <button type="submit">Sauvegarder</button>
```

2022-04-15 17:02 UTC, patou commented on become-svelte/src/lib/Form.svelte
> +  </label>
Le problème sans ça on ne peut pas faire un vrai historique car comme c'est pas sauvegarder dans une bdd et qu'on ne fait pas sur plusieurs jours. 
Le champ date n'apporte pas une grande complexité non plus.

2022-04-18 15:25 UTC, anthonylegoas commented on become-svelte/src/lib/Form.svelte
> +  </label>
Avec le champ date on ne peut pas avoir un vrai historique non plus puisque ce n'est pas sauvegardé.
Et en plus ça permet d'avoir un "historique" potentiellement faussé car on peut sélectionner une date puis enregistrer un autre imc à une date passée etc. On a pas ce soucis si on enlève le champ date, l'historique est "linéaire" puisque chaque mesure est associée au timestamp courant.

2022-04-18 18:52 UTC, patou commented on become-svelte/src/lib/Form.svelte
> +  </label>
Je comprend que l'on permet d'avoir une date pas cohérente .
Simplement le soucis c'est que le codelab dure que 3 heures sur la même journée, donc tout les historiques seront fait sur la même date , il faut donc afficher l'heure pour faire la différence et le formatage de l'heure n'est alors pas facile tant que JS n'a pas de méthode pour le faire.
Sinon, ne pas enregistrer de date et simplement afficher l'index du tableau + 1 :

1 : 45
2 : 48
3 : 46

2022-04-19 12:47 UTC, anthonylegoas approved these changes

2022-04-19 13:32 UTC, merged